// Package nvmeauth derives the per-attach NVMe-oF host identity and DH-CHAP
// credential used to make NVMe-oF exports zero-trust (see design-decisions
// ADR-0011).
//
// The host identity (NQN + host id) is derived deterministically from the
// consuming node and the volume, so the operator (which programs the target's
// allow-list) and the node (which runs `nvme connect`) compute the exact same
// value without publishing anything. The DH-CHAP key is the only real secret;
// it is generated by the operator and delivered through a Kubernetes Secret.
package nvmeauth

import (
	"crypto/rand"
	"encoding/base64"
	"encoding/binary"
	"fmt"
	"hash/crc32"

	"github.com/google/uuid"
)

// SecretKeyDHChap is the default data key under which the DH-CHAP secret is
// stored in the per-attach Kubernetes Secret. The operator may override it, in
// which case the chosen key is recorded on the NetworkExport for readers.
const SecretKeyDHChap = "dhchap-key"

// ResolveSecretKey returns configured when non-empty, otherwise the default
// DH-CHAP data key. Readers use it so the key name is never assumed.
func ResolveSecretKey(configured string) string {
	if configured != "" {
		return configured
	}
	return SecretKeyDHChap
}

// hostNamespace is the fixed UUIDv5 namespace for deriving per-attach host UUIDs.
// It is a stable, arbitrary constant (derived once from the driver domain).
var hostNamespace = uuid.NewSHA1(uuid.NameSpaceDNS, []byte("nvme.simple-zfs-csi.io"))

// HostIdentity derives the per-attach NVMe host NQN and matching host id from the
// consuming node name and the CSI volume id. The two are derived from the same
// UUID so the NVMe spec's "one host id per NQN" rule holds even though a node
// presents a distinct NQN per attachment. Both the operator and the node call
// this to obtain the same values.
func HostIdentity(nodeName, volumeID string) (hostNQN, hostID string) {
	id := uuid.NewSHA1(hostNamespace, []byte(nodeName+"/"+volumeID)).String()
	return "nqn.2014-08.org.nvmexpress:uuid:" + id, id
}

// GenerateDHChapKey returns a fresh DH-CHAP secret in the NVMe DHHC-1 format
// (`DHHC-1:00:<base64(secret||crc32)>:`), suitable for both the nvmet target's
// `dhchap_key` attribute and `nvme connect --dhchap-secret`.
func GenerateDHChapKey() (string, error) {
	secret := make([]byte, 32)
	if _, err := rand.Read(secret); err != nil {
		return "", fmt.Errorf("generate dhchap secret: %w", err)
	}
	return formatDHChapKey(secret), nil
}

// formatDHChapKey encodes raw secret bytes as a DHHC-1 no-hash key: the secret
// followed by its little-endian CRC-32 (IEEE), base64-encoded.
func formatDHChapKey(secret []byte) string {
	buf := make([]byte, len(secret)+4)
	copy(buf, secret)
	binary.LittleEndian.PutUint32(buf[len(secret):], crc32.ChecksumIEEE(secret))
	return "DHHC-1:00:" + base64.StdEncoding.EncodeToString(buf) + ":"
}
