{{- if .Values.serviceAccount.create }}
{{- if .Values.nfs.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zfs-shares.serviceAccountName" (dict "root" . "component" "nfs") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zfs-shares.labels" . | nindent 4 }}
    app.kubernetes.io/component: nfs
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.nvmeof.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zfs-shares.serviceAccountName" (dict "root" . "component" "nvmeof") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zfs-shares.labels" . | nindent 4 }}
    app.kubernetes.io/component: nvmeof
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
