//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out.
func (in *NFSClient) DeepCopyInto(out *NFSClient) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a new NFSClient.
func (in *NFSClient) DeepCopy() *NFSClient {
	if in == nil {
		return nil
	}
	out := new(NFSClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *NFSExportSpec) DeepCopyInto(out *NFSExportSpec) {
	*out = *in
	if in.Clients != nil {
		in, out := &in.Clients, &out.Clients
		*out = make([]NFSClient, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a new NFSExportSpec.
func (in *NFSExportSpec) DeepCopy() *NFSExportSpec {
	if in == nil {
		return nil
	}
	out := new(NFSExportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *NVMeoFExportSpec) DeepCopyInto(out *NVMeoFExportSpec) {
	*out = *in
	if in.AllowedHosts != nil {
		in, out := &in.AllowedHosts, &out.AllowedHosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a new NVMeoFExportSpec.
func (in *NVMeoFExportSpec) DeepCopy() *NVMeoFExportSpec {
	if in == nil {
		return nil
	}
	out := new(NVMeoFExportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ZfsShare) DeepCopyInto(out *ZfsShare) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a new ZfsShare.
func (in *ZfsShare) DeepCopy() *ZfsShare {
	if in == nil {
		return nil
	}
	out := new(ZfsShare)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a generically typed copy of the object.
func (in *ZfsShare) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *ZfsShareList) DeepCopyInto(out *ZfsShareList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZfsShare, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a new ZfsShareList.
func (in *ZfsShareList) DeepCopy() *ZfsShareList {
	if in == nil {
		return nil
	}
	out := new(ZfsShareList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a generically typed copy of the object.
func (in *ZfsShareList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *ZfsShareSpec) DeepCopyInto(out *ZfsShareSpec) {
	*out = *in
	if in.NFS != nil {
		in, out := &in.NFS, &out.NFS
		*out = new(NFSExportSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.NVMeoF != nil {
		in, out := &in.NVMeoF, &out.NVMeoF
		*out = new(NVMeoFExportSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy creates a new ZfsShareSpec.
func (in *ZfsShareSpec) DeepCopy() *ZfsShareSpec {
	if in == nil {
		return nil
	}
	out := new(ZfsShareSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ZfsShareStatus) DeepCopyInto(out *ZfsShareStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a new ZfsShareStatus.
func (in *ZfsShareStatus) DeepCopy() *ZfsShareStatus {
	if in == nil {
		return nil
	}
	out := new(ZfsShareStatus)
	in.DeepCopyInto(out)
	return out
}
